# Generated by Django 6.0.2 on 2026-02-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='hackathon.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeComplianceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=30)),
                ('esi_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_detail', to='hackathon.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCTCHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variable_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctc_history', to='hackathon.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
