# Generated by Django 6.0.2 on 2026-02-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_employeebankdetail_employeecompliancedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('it_clearance', models.BooleanField(default=False)),
                ('hr_clearance', models.BooleanField(default=False)),
                ('finance_clearance', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_workflow', to='hackathon.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RoleChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=120)),
                ('role_level', models.CharField(max_length=60)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes', to='hackathon.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('document_ref', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='hackathon.employee')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('employee', 'item_name')},
            },
        ),
    ]
