# Generated by Django 6.0.2 on 2026-02-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_exitworkflow_rolechangehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=80)),
                ('doc_number', models.CharField(blank=True, max_length=80)),
                ('doc_link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='hackathon.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('employee', 'doc_type')},
            },
        ),
    ]
